// Data: Static Content
/*----------------------------------------------------------------------------------------------------*/

/*---------- Imports ----------*/

// Config
import {
	NavItem,
	BrandClient,
	TeamClient,
	RegionClient,
	PlatformClient,
} from '@/types/index';
import names from '@/data/names';

// Images
import imgLogoCapital from '../../public/img/logo/logo_capital.png';
import imgLogoCapitalXtra from '../../public/img/logo/logo_xtra.png';
import imgLogoClassic from '../../public/img/logo/logo_classic.png';
import imgLogoRadioX from '../../public/img/logo/logo_radiox.png';
import imgLogoPopBuzz from '../../public/img/logo/logo_popbuzz.png';
import imgLogoHeart from '../../public/img/logo/logo_heart.png';
import imgLogoSmooth from '../../public/img/logo/logo_smooth.png';
import imgLogoLbc from '../../public/img/logo/logo_lbc.png';
import imgLogoGold from '../../public/img/logo/logo_gold.png';
import imgLogoGlobal from '../../public/img/logo/logo_global.png';

// Scripts
import { strCapitalize } from '@/lib/utils';

/*---------- Static Content ----------*/

// Metadata
export const staticMetadata = {
	title: 'Brainstorm Hub',
	description: 'Generated by create next app',
};

// Navigation
export const staticNavHeader: NavItem[] = [
	{ name: 'Calendar', href: '/calendar', target: '_self' },
	// { name: 'Teams', href: '/team', target: '_self' },
	// { name: 'Brands', href: '/brand', target: '_self' },
	{ name: 'Users', href: '/user', target: '_self' },
];

// Brands
export const staticBrands: BrandClient[] = [
	{
		id: 'capital',
		name: 'Capital',
		imageUrl: imgLogoCapital.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'xtra',
		name: 'Capital Xtra',
		imageUrl: imgLogoCapitalXtra.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'classic',
		name: 'Classic FM',
		imageUrl: imgLogoClassic.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'radiox',
		name: 'Radio X',
		imageUrl: imgLogoRadioX.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'popbuzz',
		name: 'PopBuzz',
		imageUrl: imgLogoPopBuzz.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'heart',
		name: 'Heart',
		imageUrl: imgLogoHeart.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'smooth',
		name: 'Smooth',
		imageUrl: imgLogoSmooth.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'lbc',
		name: 'LBC',
		imageUrl: imgLogoLbc.src,
		teams: [],
		access: 'user',
	},
	{
		id: 'gold',
		name: 'Gold',
		imageUrl: imgLogoGold.src,
		teams: [],
		access: 'user',
	},
];

// Teams
export const staticTeams: TeamClient[] = [
	{
		id: 'capital',
		name: 'Team Capital',
		imageUrl: imgLogoCapital.src,
		brands: ['capital', 'xtra', 'classic', 'radiox', 'popbuzz'],
		platforms: ['in-person', 'virtual'],
		duration: [
			{ label: '20 Minutes', value: 20 },
			{ label: '30 Minutes', value: 30 },
			{ label: '40 Minutes', value: 40 },
			{ label: '1 Hour', value: 60 },
		],
		times: [
			{
				id: 'monday',
				timeStart: '09:30',
				timeEnd: '10:30',
			},
			{
				id: 'tuesday',
				timeStart: '09:30',
				timeEnd: '10:30',
			},
			{
				id: 'wednesday',
				timeStart: '09:30',
				timeEnd: '10:30',
			},
			{
				id: 'thursday',
				timeStart: '09:30',
				timeEnd: '10:30',
			},
			{
				id: 'friday',
				timeStart: '09:30',
				timeEnd: '10:30',
			},
		],
		access: 'user',
	},
	{
		id: 'heart',
		name: 'Team Heart',
		imageUrl: imgLogoHeart.src,
		brands: ['heart', 'smooth', 'lbc', 'gold'],
		platforms: ['in-person', 'virtual'],
		duration: [
			{ label: '20 Minutes', value: 20 },
			{ label: '30 Minutes', value: 30 },
			{ label: '40 Minutes', value: 40 },
			{ label: '1 Hour', value: 60 },
		],
		times: [
			{
				id: 'monday',
				timeStart: '12:00',
				timeEnd: '12:30',
			},
			{
				id: 'tuesday',
				timeStart: '12:00',
				timeEnd: '12:30',
			},
			{
				id: 'wednesday',
				timeStart: '12:00',
				timeEnd: '12:30',
			},
			{
				id: 'thursday',
				timeStart: '12:00',
				timeEnd: '12:30',
			},
			{
				id: 'friday',
				timeStart: '12:00',
				timeEnd: '12:30',
			},
		],
		access: 'user',
	},
	{
		id: 'default',
		name: 'Team Combined',
		imageUrl: imgLogoGlobal.src,
		brands: [],
		platforms: ['in-person', 'virtual'],
		duration: [
			{ label: '30 Minutes', value: 30 },
			{ label: '1 Hour', value: 60 },
		],
		times: [
			{
				id: 'monday',
				timeStart: '10:30',
				timeEnd: '12:00',
			},
			{
				id: 'tuesday',
				timeStart: '10:30',
				timeEnd: '12:00',
			},
			{
				id: 'wednesday',
				timeStart: '10:30',
				timeEnd: '12:00',
			},
			{
				id: 'thursday',
				timeStart: '10:30',
				timeEnd: '12:00',
			},
			{
				id: 'friday',
				timeStart: '10:30',
				timeEnd: '12:00',
			},
		],
		access: 'user',
	},
];

// Regions
export const staticRegions: RegionClient[] = [
	{
		id: 'leicester-square',
		name: 'Leicester Square',
		platforms: ['teams-meet-up', 'all-in-the-room'],
	},
	{
		id: 'regional',
		name: 'Regional',
		platforms: ['all-in-the-room'],
	},
];

// Platforms
export const staticPlatforms: PlatformClient[] = [
	{
		id: 'all-in-the-room',
		name: 'All in the Room',
		teamsUrl:
			'https://teams.microsoft.com/l/meetup-join/19%3ameeting_NzcxMGIyMmEtODVhMC00MzhkLWFhZGUtYmIxOWZkOGIyMWQ3%40thread.v2/0?context=%7b%22Tid%22%3a%22be189d14-1d13-4148-9edf-47fff7e918a8%22%2c%22Oid%22%3a%2259695bee-ac3b-4dc5-91d8-c1c3d967a3ca%22%7d',
	},
	{
		id: 'teams-meet-up',
		name: 'Teams Meet Up',
		teamsUrl:
			'https://teams.microsoft.com/l/meetup-join/19%3a931db11ebdd940e8b89079038109c416%40thread.tacv2/1625132119009?context=%7b%22Tid%22%3a%22be189d14-1d13-4148-9edf-47fff7e918a8%22%2c%22Oid%22%3a%22093883ec-1f59-4f2a-833c-f41ba3bde151%22%7d',
	},
];

// Event Onboarding
export const staticEventOnboarding = [
	// Intro
	{
		id: 'intro',
		title: `Create a New ${strCapitalize(names.event)}`,
		body: `
			<p>Curabitur aliquet quam id dui posuere blandit. Donec rutrum congue leo eget malesuada. Curabitur aliquet quam id dui posuere blandit.</p>
			<p>Donec sollicitudin molestie malesuada. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Pellentesque in ipsum id orci porta dapibus. Nulla quis lorem ut libero.</p>
			<p>Malesuada feugiat. Sed porttitor lectus nibh. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.</p>
		`,
		prev: false,
		next: 'Next',
	},
	// Response Time
	{
		id: 'response-time',
		title: 'Response Time',
		body: `
			<p>How long would you like to book your session for?</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// Session Name
	{
		id: 'name',
		title: `${strCapitalize(names.event)} Name`,
		body: `
			<p>What’s the title of your ${names.brief}?</p>
		`,
		bodySalesforce: `
			<p>
				Wait! It looks like you're on a tight deadline
			</p>
			<p>
				Did you know: if you had a longer time frame lorem ipsum
				dolor sit amet, consectetur adipiscing elit. Curabitur
				arcu erat, sed sit amet dui.
			</p>
			<p>
				Your best item is to head to Salesforce to submit a fast
				track brief.
			</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// Brands
	{
		id: 'brands',
		title: `${strCapitalize(names.brands)}`,
		body: `
			<p>Which brands are you working with?</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// Team / Region
	{
		id: 'region',
		title: `${strCapitalize(names.team)} / ${strCapitalize(names.region)}`,
		body: `
			<p>Which region are you working from?</p>
		`,
		bodyBadCombo: `
			<p>
				Wait! It looks like we can't combine these brands under one team
			</p>
			<p>
				Please contact a team lead to discuss your options.
			</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// Platforms
	{
		id: 'platform',
		title: `${strCapitalize(names.team)} / ${strCapitalize(names.region)}`,
		body: `
			<p>Which platform are you working from?</p>
		`,
		bodyBadCombo: `
			<p>
				Wait! It looks like there are no platforma available for this team and region
			</p>
			<p>
				Please contact a team lead to discuss your options.
			</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// Duration
	{
		id: 'duration',
		title: `${strCapitalize(names.duration)}`,
		body: `
			<p>How long is your ${names.event}?</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// About
	{
		id: 'about',
		title: `${strCapitalize(names.about)}`,
		body: `
			<p>Write a few sentences about the ${names.event}.</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// Datetime
	{
		id: 'datetime',
		title: 'Time Slot',
		body: `
			<p>Choose a time from the slots available.</p>
		`,
		prev: 'Previous',
		next: 'Next',
	},
	// Submit
	{
		id: 'submit',
		title: 'Summary',
		body: false,
		prev: 'Previous',
		submit: 'Submit',
	},
];
